# Generated by Django 2.1.4 on 2019-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero', models.FloatField(max_length=30)),
                ('febrero', models.FloatField(max_length=30)),
                ('marzo', models.FloatField(max_length=30)),
                ('abril', models.FloatField(max_length=30)),
                ('mayo', models.FloatField(max_length=30)),
                ('junio', models.FloatField(max_length=30)),
                ('julio', models.FloatField(max_length=30)),
                ('agosto', models.FloatField(max_length=30)),
                ('septiembre', models.FloatField(max_length=30)),
                ('octubre', models.FloatField(max_length=30)),
                ('noviembre', models.FloatField(max_length=30)),
                ('diciembre', models.FloatField(max_length=30)),
                ('total', models.FloatField(max_length=30)),
            ],
        ),
    ]
